"use client"

import {
  SiGithub,
  SiX,
  SiReact,
  SiTailwindcss,
  SiFramer,
  SiApple,
  SiNextdotjs,
  SiTypescript,
  SiJavascript,
  SiNodedotjs,
  SiPython,
  SiDocker,
  SiAmazon,
  SiVercel,
  SiFigma,
  SiPostgresql,
  SiMongodb,
  SiFirebase,
  SiGit,
} from "react-icons/si"

export const Icons = {
  gitHub: SiGithub,
  twitter: SiX,
  react: SiReact,
  tailwind: SiTailwindcss,
  framerMotion: SiFramer,
  apple: SiApple,
  nextjs: SiNextdotjs,
  typescript: SiTypescript,
  javascript: SiJavascript,
  nodejs: SiNodedotjs,
  python: SiPython,
  docker: SiDocker,
  aws: SiAmazon,
  vercel: SiVercel,
  figma: SiFigma,
  postgresql: SiPostgresql,
  mongodb: SiMongodb,
  firebase: SiFirebase,
  git: SiGit,
}
